[tool.poetry]
name = "nasa-hackaton"
version = "0.1.0"
description = ""
authors = ["Rhuan Marques <rhuanleonardobm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
<<<<<<< HEAD
=======
pydantic = "^2.9.2"
>>>>>>> 12a2697d736417743b60c95e3d75ae25eb26c86b
pandas = "^2.2.3"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
